# Inicio
name: Refugio VirtuaMental de un Internauta
description: Blog de Jesús Ángel Samitier sobre desarrollo, tecnología y opinión
themeJekyll: Boira
version: 2.0.0
timezone: Europe/Madrid

# Configuracion
url: http://eckelon.net/blog
baseurl:
paginate: 5
paginate_path: "page:num"
highlighter: pygments
markdown: kramdown
urliconosheader: ../img/social-sprite.svg
urliconos: /img/social-sprite.svg
gems: [jekyll-paginate]
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

permalink: /:categories/:title.html
#informatica-e-internet/how-to/como-desactivar-la-memoria-virtual-en-snow-leopard.html

# Redes Sociales
author: Jesús Ángel Samitier
twittername: eckelon
twitter: https://twitter.com/eckelon
GitHub: https://github.com/eckelon/

exclude: [ config.codekit, .gitignore, .sass-cache, .tweet-cache, node_modules, package.json, gulpfile.js, _drafts ]
